on:
  push:
    branches:
      - main
      - test
      - dev

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      ENVIRONMENT: ${GITHUB_REF##*/}
      WORKSPACE_NAME: '${{ github.event.repository.name }}-${GITHUB_REF##*/}'

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend-config "tf_state_workspace=${{ env.WORKSPACE_NAME }}"
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="tf_state_workspace=${{env.WORKSPACE_NAME}}" -var="environment=${{env.ENVIRONMENT}}" -var="projectName=${{env.PROJECT_NAME}}" -var="app_client_id=${{secrets.DEPLOYMENT_CREDS_ID}}" -var="app_client_secret=${{secrets.DEPLOYMENT_SECRETS_ID}}" || terraform destroy -auto-approve